"""Sphinx configuration file."""

# -*- coding: utf-8 -*-
import os
from recommonmark.parser import CommonMarkParser


project = u'Test Project'
copyright = u'2019, cytopia'
author = u'cytopia'

# The short X.Y version
version = u'1.0'
# The full version, including alpha/beta/rc tags
release = u'1.0'


# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.todo'
]

todo_include_todos = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = [
    u'_build/*',
    u'_includes/**',
    u'venv/*',
    u'Thumbs.db',
    u'.DS_Store'
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

rst_epilog = """
.. |psf| replace:: Devilbox
"""


# -- Options for Link check -------------------------------------------------

# http://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-the-linkcheck-builder
linkcheck_ignore = [
    r'http(s)?://localhost(/)?.*',
    r'http(s)?://127\.0\.0\.1(/)?.*',
    r'http(s)?://.+\.loc$',
    r'http(s)?://.+\.loc/.+$'
]
linkcheck_retries = 5
linkcheck_timeout = 60
linkcheck_anchors = True

html_theme = 'default'

# https://github.com/snide/sphinx_png_theme#using-this-theme-locally-then-building-on-read-the-docs
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'
if not on_rtd:
    import sphinx_rtd_theme
    html_theme = 'sphinx_rtd_theme'
    html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

# https://sphinx-rtd-theme.readthedocs.io/en/latest/configuring.html#project-wide-configuration
html_theme_options = {
    'canonical_url': '',
    'analytics_id': '',
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': 5,
}

# If true, “Created using Sphinx” is shown in the HTML footer. Default is True.
html_show_sphinx = False

# Output file base name for HTML help builder.
htmlhelp_basename = 'testdoc'


def setup(app):
    """Include custom css file."""
    pass
